### PR TITLE
Add recommendation to persistently disable SELinux on CentOS/RHEL

### PR DESCRIPTION
**Pull request by henn**

### CODE REVIEW

**Comment by gsilvis** [comment]
At first I thought 'Why are we now recommending this?'.  But then I noticed that we were already recommending it.  Given that it's there, I agree, we should say how to do it.  +1

**Comment by SahilTikale** [comment]
All tests failing. Once fixed I will give a +1

**Comment by gsilvis** [comment]
I don't know why these are failing, but this is a pure documentation change, so I don't think it's @henn's fault

**Comment by gsilvis** [comment]
Rerunning tests...

**Comment by gsilvis** [comment]
@SahilTikale, you gave a +1 conditional on tests passing, so I'll merge now.

**Pull request merged**
