### PR TITLE
Restapi docfix

### PR DESCRIPTION
**Pull request by zenhack**
We were still talking about form data -- it's been quite a while since we switched to JSON.

### CODE REVIEW

**Comment by gsilvis** [comment]
Oh hey, we actually use JSON now!  +1

**Comment by zenhack** [comment]
@henn, @lokI8, This also needs a second review. This one should be pretty quick.

**Comment by zenhack** [comment]
Oh, worth noting: I also started expanding the documentation for other stuff in `rest_api.md`. I'd like to move in a direction where this file is a full reference, whereas now it documents arguments and urls and such, but you have to know the semantics already.

**Comment by lokI8** [comment]
+1, merging. looks good

**Pull request merged**
