### PR TITLE
Add brocade option to switch_register CLI

### PR DESCRIPTION
**Pull request by knikolla**
The driver was merged but brocade was missing a CLI option
to register the driver.

### CODE REVIEW

**Comment by SahilTikale** [comment]
looks good
+1

**Comment by henn** [comment]
Hey Kristi

Any chance you could add a quick example somewhere? Specifically, I have no idea what I would enter for `interface_type`.

Maybe a good place for that would be to add a "Brocade" blurb to [docs/network-drivers.md](https://github.com/CCI-MOC/haas/blob/master/docs/network-drivers.md) and something in the CLI error text?

**Comment by knikolla** [comment]
@henn added note in cli error text. I'll do the network-drivers documentation in a separate pull request.

**Comment by SahilTikale** [comment]
@henn 
I tried the command line and it works. 

If you have no other objections kindly approve this so that we can merge it asap.

**Comment by henn** [comment]
Kristi- do you know when you'll be able to submit the documentation?

**Comment by henn** [comment]
Kristi and I chatted, and we should be able to get driver documentation within the next 2 weeks as part of #604. +1 and merging.

**Pull request merged**
