### PR TITLE
Minor fix to wsgi configuration 

### PR DESCRIPTION
**Pull request by SahilTikale**
This fix is required to make the latest code work in production mode.

### CODE REVIEW

**Comment by SahilTikale** [comment]
@zenhack 
@knikolla 
Very small PR.
review, aproove, merge.

**Comment by zenhack** [comment]
suggestion: add an explanation of the option, right next to the explanation of `AllowEncodedSlashes`.

**Comment by knikolla** [comment]
+1

**Comment by SahilTikale** [comment]
@zenhack 
This is a small one. Can you look at it and give it a +1 so that we can merge it. 

Thanks

**Comment by zenhack** [comment]
@SahilTikale, I made a comment when you first opened this. please address it.

**Comment by SahilTikale** [comment]
@zenhack 
Updated INSTALL.rst with relevant comments.
Let me know if anything else is needed.

**Comment by zenhack** [comment]
+1; merging.

**Pull request merged**
