### PR TITLE
add uuid/base_img to show_headnode

### PR DESCRIPTION
**Pull request by xuhang57**
Added uuid and base_mg to show_headnode here.

I cannot have it output the virtual machine name for now, since, according to Sahil, I need to setup libvirt first and then I can do something with the name of virtual machine in show_headnode(). 

**For the unit test**, I am having trouble for write a unit test for the uuid in show_headnode() since uuid is a unique id and I cannot hard-code it in the unit test script for testing. 

Any suggestion would be much appreciated.

### CODE REVIEW

**Comment by henn** [comment]
+1

**Comment by SahilTikale** [comment]
I tested the code. Just by copying the lines from this api.py to mine, it works as expected.
But when I pulled the branch and tried to rerun the test it is giving errors.

@xuhang57 have you changed anything else in the api.py. other than adding the two lines. 
api.py for this branch is broken.

**Comment by henn** [comment]
@SahilTikale Any update on this based on our conversations yesterday?

**Comment by SahilTikale** [comment]
Hi Tested the pull request. It works as intended. 
+1 from me.

**Pull request merged**
