### PR TITLE
Remove erroneous information about apache config.

### LINKED ISSUE #440: INSTALL.rst suggests using AllowEncodedSlashes NoDecode on newer versions of apache, but this breaks things
you end up sending things like gi1%2F0%2F13 to the switch. we should update the docs to correct this

### PR DESCRIPTION
**Pull request by zenhack**
Resolves #440.

### CODE REVIEW

**Comment by zenhack** [comment]
//cc @gsilvis

**Comment by gsilvis** [comment]
Do we fully understand the situation here?  I know we added that to make something work.  Is there no setup where it's required?

**Comment by zenhack** [comment]
We never actually tried it with a more recent apache until I set it up on the Cisco gear. @henn just thought would be better because it was slightly more conservative. Unfortunately it turns out you need to decode the slashes for this to work, so the documentation was strictly incorrect.

**Comment by gsilvis** [comment]
Okay.  +1

**Comment by lokI8** [comment]
Okay. I remember this being a security concern to include slashes, but we need them to match switch configs... should we make an issue so that we remember this is a potential hole? Otherwise +1

**Comment by zenhack** [comment]
It can be a security issue in other contexts, e.g. if the argument in question is an path name, someone might pass something like `../../etc/passwd` to break out of your document root. in this case that's not true, so having slashes in the input isn't dangerous.

**Comment by lokI8** [comment]
Fair enough, that makes sense. +1, merging

**Pull request merged**
