### PR TITLE
Sorts output that provides lists

### PR DESCRIPTION
**Pull request by SahilTikale**
Addresses issue #500 
Short, simple PR. 
@henn @knikolla 
If you have time for reviewing this.

### CODE REVIEW

**Comment by knikolla** [comment]
+1, Looks good.

**Comment by pjd-nu** [comment]
+1

**Comment by zenhack** [comment]
So, just noticed this because it caused some (utterly trivial) merge conflicts with #561. This is fine, but I would point out the existence of SQL's `ORDER BY`; you can have the DB do the sorting.

**Comment by ron-unrau** [comment]
Do you know if SQLAlchemy exports/supports 'ORDER BY'? I would like to use it, but I have no idea how it would look in python...

**Comment by zenhack** [comment]
Quoting Ron Unrau (2016-04-09 01:46:10)

>    Do you know if SQLAlchemy exports/supports 'ORDER BY'? I would like to
>    use it, but I have no idea how it would look in python...

It's just an `.order_by` method on the query object. We might have some
examples of this in the HaaS source tree already, but if not check out
the SQLAlchemy docs.

**Pull request merged**
