### PR TITLE
Fix package dependencies in docs

### PR DESCRIPTION
**Pull request by starbops**
Fix package dependencies in docs

`vconfig` and `net-tools` are needed in CentOS 7
(cherry picked from commit 33ea452)

### CODE REVIEW

**Comment by SahilTikale** [comment]
@henn @knikolla 

Since we will be soon getting the VPN implementation, should be include this changes for the time being. 
What do you guys think about this PR ?

**Comment by knikolla** [comment]
I think they should be included, if they reflect the current state of HaaS.

**Comment by SahilTikale** [comment]
+1 
@knikolla 
if you find it ok and would want to +1, we can close this

**Comment by henn** [comment]
I agree with @knikolla 

Can one of you guys confirm that we needed to install these packages on CentOS? Should we update the ansible?

@SahilTikale

**Comment by SahilTikale** [comment]
Yes we need this packages. I had to install them during one of the HaaS installation.
Until we get the VPN feature working, we have decided to continue with the current way of creating bridges. To that end this PR is relevant.

**Comment by henn** [comment]
Would you like to +1 then so we can merge?

**Comment by SahilTikale** [comment]
@henn Can you please +1 this so that we can merge it.
Unless you have further questions, that is.

**Comment by knikolla** [comment]
+1

**Comment by SahilTikale** [comment]
merging

**Pull request merged**
