### PR TITLE
Fixes create_admin_user cli command

### PR DESCRIPTION
**Pull request by knikolla**
After the alembic refactoring the command was broken.

### CODE REVIEW

**Comment by gsilvis** [comment]
Having tests for this sort of stuff would be fantastic... oh well.

**Comment by knikolla** [comment]
@SahilTikale this should fix the issue you encountered.

**Comment by gsilvis** [comment]
+1

**Comment by gsilvis** [comment]
@SahilTikale you can +2 and merge, if it looks good

**Comment by SahilTikale** [comment]
+2 merging

**Pull request merged**
