### PR TITLE
Make sleep() in serve_networks() tunable

### PR DESCRIPTION
**Pull request by ryabouza**
Also add some documentation.

This is in response to issue #318.

### CODE REVIEW

**Comment by zenhack** [comment]
This looks fine, +1.

@gsilvis, @lokI8, can one of you +2?

**Comment by ryabouza** [comment]
:four_leaf_clover:

**Comment by gsilvis** [comment]
This is certainly fine, though until someone calls it with a custom parameter it does nothing.  +1

**Comment by zenhack** [comment]
Okay merging.

We've got some things going into devel and others master -- I'll make sure that story is coherent some time today.

**Pull request merged**
