### PR TITLE
Remove user-aware code from core, add per-request IDs to logs.

### PR DESCRIPTION
**Pull request by zenhack**
@gsilvis, @knikolla and I talked about this on IRC. The commit message describes the problem and my solution. I came across this while working on the keystone stuff and was bothered by it enough to insist on fixing it.

Could you two review? Opinions from others are also welcome (@henn?).

### CODE REVIEW

**Comment by zenhack** [comment]
I plan to build the keystone stuff on top of this; I'm doing it now because I didn't want to add `get_user` to another backend, as I strongly object to the construct.

**Comment by gsilvis** [comment]
A little surprised that flask doesn't have this functionality.  +1 though.

**Comment by zenhack** [comment]
If we someday feel ambitious we could pull that class into it's own package and distributed it separately; maybe have it listed on the flask extensions index. Out of scope for the time being.

**Comment by knikolla** [comment]
Looks good, +1.

**Pull request merged**
