### PR TITLE
Add mock OBM driver as well as null network allocator to default dev config

### PR DESCRIPTION
**Pull request by henn**
This way, most devs without real hardware should be able to just grab the
config and run without adjustments.

### CODE REVIEW

**Comment by rahulbahal7** [comment]
+1 Reviewed the changes. Also should there be a note in the README or somewhere regarding this?

**Comment by henn** [comment]
@rahulbahal7 - We have this part of the README which points to the directory:
```rst
* `examples <examples/>`_ contains examples of config files, templates for creating headnode VM images and a script to register nodes with HaaS.
```

Also, HACKING.rst points to the config file location (which I just updated as part of the PR since it was outdated).

Do you think that is sufficient, or do you think we should display the config examples more prominently?

**Comment by rahulbahal7** [comment]
I missed the pointer in README and the current update in HACKING.rst also makes it prominent. Thanks!

**Comment by henn** [comment]
Merging due to +1.

**Pull request merged**
