### PR TITLE
Add a node_power_off API call.

### PR DESCRIPTION
**Pull request by zenhack**
Might be nice to save some power.

//cc @henn @gsilvis @lokI8

### CODE REVIEW

**Comment by gsilvis** [comment]
What will this return if it's already off?

**Comment by lokI8** [comment]
Apparently  "raise OBMError('Could not power off node %s', self.label)"

**Comment by gsilvis** [comment]
I mostly meant that we should document that.  (It might also be nice to say something like 'the machine is already off' if possible.)

**Comment by zenhack** [comment]
Quoting George Silvis, III (2015-08-28 14:41:11)

>    I mostly meant that we should document that. (It might also be nice to
>    say something like 'the machine is already off' if possible.)

ipmitool seems to return successfully regardless of whether the machine
is already off. I can add something to this effect to the docs.

**Comment by zenhack** [comment]
Docs update.

**Comment by gsilvis** [comment]
+1

**Comment by gsilvis** [comment]
Worth noting:  this change will have to be integrated into #484

**Comment by zenhack** [comment]
Yep. I mentioned that to @SahilTikale already.

**Comment by henn** [comment]
I fully agree that we should have this internally, and potentially run
it automatically when a node is free'd to consume less power/cooling.

That said, I'm not sure how customers would use it for allocated
machines. If someone is paying for a node, when would they want it to be
powered off? Ideally, they would free it and not use it anymore.

We should be careful when adding something to the API, since it will be
difficult to take away later.

**Comment by lokI8** [comment]
I definitely think this is beneficial, seeing as admins and users have access to the same cli... 

It would be nice if this was included in free node, but this is what we have for now, and we don't want to keep machines running. 

I'd like to approve, code looks good, but feel awkward going against Jay

**Comment by henn** [comment]
My objection wasn't strong and consensus seems to be to include this, so merging.

Also - we'll need to add tests for this once we have IPMI tests (see #524).

**Pull request merged**
