### PR TITLE
Add Travis CI status to README

### PR DESCRIPTION
**Pull request by henn**

### CODE REVIEW

**Comment by shwsun** [comment]
I took a look, adding travis status is very cool. Can I give a +1 or it has to be someone in the core team?

**Comment by knikolla** [comment]
+1

**Comment by henn** [comment]
@shwsun: You can always give a +1 if you think something is ready to be merged!

Per our [developer guidelines](https://github.com/CCI-MOC/haas/blob/master/docs/developer-guidelines.md), the requirements are normally: 2 * +1's, and two of the folks involved (either 2 reviewers or one of the submitters) in the process need to be "core" members.  For documentation, we only need 1 * +1.

Since you commented, I'll wait for you to give any feedback or a +1.

**Comment by shwsun** [comment]
+1 
Thanks for the clarifications.

**Comment by henn** [comment]
Merging due to 2 * +1's.

**Pull request merged**
